// SAA-C03 Domain 4: Design Cost-Optimized Architectures (20% weight) — 15 unique questions
const D = "saa-d4", DN = "Domain 4: Design Cost-Optimized Architectures";
export default [
{d:D,dn:DN,qt:"single",s:"A company runs a web application on EC2 instances that have steady, predictable usage 24/7 for the next 3 years. They are currently using On-Demand instances and want to reduce compute costs significantly. Which purchasing option offers the GREATEST savings?",
o:["Spot Instances for up to 90% discount","3-year All Upfront Reserved Instances for up to 72% discount compared to On-Demand","EC2 Savings Plans with no upfront payment","Dedicated Hosts with reserved pricing"],
c:["B"],e:"For steady, predictable 24/7 workloads with a known 3-year commitment, All Upfront Reserved Instances provide the deepest discount (up to 72% vs On-Demand). Spot Instances can be interrupted and aren't suitable for always-on production. Savings Plans offer flexibility but slightly lower maximum discount. Dedicated Hosts are for licensing or compliance, not cost optimization.",df:"Standard",u:"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-reserved-instances.html"},

{d:D,dn:DN,qt:"single",s:"A batch video transcoding pipeline can tolerate interruptions and automatically retry failed jobs. Individual jobs take 10-30 minutes. The company wants to minimize compute costs. Which EC2 purchasing option should they use?",
o:["On-Demand Instances for reliability and availability","Spot Instances with checkpointing for up to 90% cost savings","Reserved Instances with a 1-year term","Dedicated Instances for consistent performance"],
c:["B"],e:"Spot Instances provide up to 90% discount over On-Demand and are ideal for fault-tolerant, interruptible workloads like batch processing and video transcoding. With short job durations (10-30 min) and automatic retry, the impact of Spot interruptions is minimal. Checkpointing ensures no work is lost if an instance is reclaimed.",df:"Standard",u:"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html"},

{d:D,dn:DN,qt:"single",s:"A company stores 100TB of log data in S3 Standard. Analysis shows that logs older than 30 days are accessed only for compliance audits once a year, and logs older than 365 days are never accessed but must be retained for 7 years. What is the MOST cost-effective storage strategy?",
o:["Keep all data in S3 Standard for fastest access when needed","Create lifecycle rules: move to S3 Standard-IA after 30 days, then to S3 Glacier Deep Archive after 365 days","Move all data immediately to S3 Glacier to reduce costs","Enable S3 Intelligent-Tiering and let AWS optimize automatically"],
c:["B"],e:"S3 Lifecycle rules automate tiered storage: Standard for active data (first 30 days), Standard-IA for infrequently accessed data (up to 63% cheaper, suitable for yearly audits), and Glacier Deep Archive for long-term compliance retention (up to 95% cheaper, with 12-hour retrieval acceptable for archived logs).",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html"},

{d:D,dn:DN,qt:"single",s:"A development team has unpredictable S3 access patterns — some objects are accessed frequently for a few days, then not at all for months, with no predictable schedule. They want to minimize storage costs without managing lifecycle rules. Which storage class is BEST?",
o:["S3 Standard for consistent performance","S3 One Zone-IA for reduced redundancy at lower cost","S3 Intelligent-Tiering for automatic cost optimization based on access patterns","S3 Glacier Instant Retrieval for infrequent access with fast retrieval"],
c:["C"],e:"S3 Intelligent-Tiering automatically moves objects between access tiers based on actual usage patterns. Frequently accessed objects stay in the Frequent Access tier, and objects not accessed for 30+ days move to Infrequent Access (40% savings), then to Archive (68% savings) after 90 days. There are no retrieval fees or lifecycle management needed.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/intelligent-tiering.html"},

{d:D,dn:DN,qt:"multiple",s:"A company wants to establish a cost governance framework across their AWS Organization with 20 accounts. They need proactive cost alerts and retroactive cost analysis. Which TWO services should they implement? (Select TWO.)",
o:["AWS Budgets with alert thresholds and SNS notifications for proactive cost management","AWS Cost Explorer with filtering by account, service, and tags for retroactive analysis","AWS Trusted Advisor for technical best practice recommendations","Amazon CloudWatch billing alarms for regional spend monitoring","AWS Pricing Calculator for estimating future workload costs"],
c:["A","B"],e:"AWS Budgets allows setting custom cost and usage thresholds with automated alerts via SNS/email when forecasted or actual spending exceeds limits — this is proactive. Cost Explorer provides visualization, filtering, and trend analysis of historical spending across accounts, services, and custom tags — this is retroactive analysis.",df:"Standard",u:"https://docs.aws.amazon.com/cost-management/latest/userguide/budgets-managing-costs.html"},

{d:D,dn:DN,qt:"single",s:"A company's VPC generates 5TB of monthly data transfer charges from EC2 instances accessing S3 through a NAT Gateway. How can they eliminate this cost while maintaining private connectivity to S3?",
o:["Use S3 Transfer Acceleration to reduce data transfer costs","Replace the NAT Gateway with a cheaper NAT Instance","Create an S3 Gateway VPC Endpoint which is free and eliminates NAT Gateway charges for S3 traffic","Move the EC2 instances to a public subnet and access S3 directly via the internet"],
c:["C"],e:"S3 Gateway VPC Endpoints are free — no hourly charge and no data processing charge. S3 traffic routed through the endpoint bypasses the NAT Gateway entirely, eliminating both the NAT Gateway data processing charge ($0.045/GB) and the Gateway hourly charge for that traffic. This saves $225/month on 5TB of S3 traffic alone.",df:"Standard",u:"https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html"},

{d:D,dn:DN,qt:"single",s:"A company runs EC2 instances that are significantly over-provisioned. CPU utilization averages 10-15% across the fleet. The operations team wants a data-driven approach to rightsize instances. Which AWS tool provides specific rightsizing recommendations?",
o:["Amazon CloudWatch CPU utilization dashboards to manually assess instance sizing","AWS Compute Optimizer which analyzes utilization patterns and recommends optimal instance types","AWS Cost Explorer general spending reports","AWS Trusted Advisor basic checks for underutilized instances"],
c:["B"],e:"AWS Compute Optimizer uses machine learning to analyze CloudWatch metrics (CPU, memory, network, disk) and recommends optimal EC2 instance types based on actual workload patterns. It provides specific recommendations like 'change from m5.2xlarge to m5.large' with projected savings. Trusted Advisor only flags instances below a threshold, without specific sizing recommendations.",df:"Standard",u:"https://docs.aws.amazon.com/compute-optimizer/latest/ug/what-is-compute-optimizer.html"},

{d:D,dn:DN,qt:"single",s:"A startup is building a new serverless API backend. They expect highly variable traffic — from 10 requests per minute during off-hours to 10,000 per second during viral events. They want zero idle costs. Which architecture minimizes cost while handling scale?",
o:["EC2 Auto Scaling group with minimum capacity of 2 instances behind an ALB","API Gateway + Lambda + DynamoDB on-demand mode for a fully pay-per-use stack","ECS Fargate with minimum 2 running tasks and Application Auto Scaling","Elastic Beanstalk with a t3.small instance and Auto Scaling"],
c:["B"],e:"API Gateway + Lambda + DynamoDB on-demand is fully serverless with no idle costs. You pay only per API call, per Lambda invocation (per 1ms), and per DynamoDB read/write request. During zero traffic, the cost is $0. All three services auto-scale to handle sudden bursts without pre-provisioning. EC2/ECS/Beanstalk all have minimum running costs.",df:"Standard",u:"https://docs.aws.amazon.com/lambda/latest/dg/welcome.html"},

{d:D,dn:DN,qt:"single",s:"A company wants to archive 500TB of compliance data that will never be accessed under normal circumstances but must be retrievable within 12 hours for regulatory audits. What is the MOST cost-effective storage option?",
o:["S3 Standard-IA for infrequent access at reduced cost","S3 Glacier Flexible Retrieval with standard retrieval (3-5 hours)","S3 Glacier Deep Archive with standard retrieval (within 12 hours) at the lowest cost","Amazon EFS with Infrequent Access storage class"],
c:["C"],e:"S3 Glacier Deep Archive is the lowest-cost storage class in AWS, designed for long-term data archiving. At ~$1/TB/month, it costs about 95% less than S3 Standard. Standard retrieval takes up to 12 hours, which meets the requirement. Glacier Flexible Retrieval costs more (~$3.60/TB/month). For pure archival with 12-hour retrieval tolerance, Deep Archive is optimal.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html"},

{d:D,dn:DN,qt:"single",s:"A company is migrating workloads to AWS and wants flexible compute savings without committing to specific instance types or regions. They need at least a 1-year commitment. Which purchasing option provides the BEST flexibility with meaningful savings?",
o:["Standard Reserved Instances for specific instance types in specific regions","Compute Savings Plans for flexible savings across instance families, sizes, and regions","Convertible Reserved Instances that can be exchanged for different types","Spot Instances for the highest possible discount"],
c:["B"],e:"Compute Savings Plans offer up to 66% savings with maximum flexibility — they apply to any EC2 instance family, size, OS, tenancy, and region, as well as Fargate and Lambda usage. Standard RIs are locked to specific instance type and region. Convertible RIs offer flexibility but lower discount. Spot Instances can't guarantee availability.",df:"Standard",u:"https://docs.aws.amazon.com/savingsplans/latest/userguide/what-is-savings-plans.html"},

{d:D,dn:DN,qt:"multiple",s:"A media company stores user-uploaded videos in S3. They want to minimize costs by: (1) serving videos efficiently to global viewers and (2) automatically archiving videos not viewed for 90 days. Which TWO solutions address both requirements? (Select TWO.)",
o:["CloudFront CDN to cache and serve videos from edge locations, reducing S3 transfer costs","S3 Lifecycle rule to transition objects to Glacier Flexible Retrieval after 90 days of no access","S3 Requester Pays bucket so viewers pay for data transfer","Enable S3 Object Lock to prevent costly accidental deletions","Compress all videos with H.265 codec before uploading to reduce storage size"],
c:["A","B"],e:"CloudFront reduces costs by caching videos at edge locations — S3 transfer to CloudFront is free, and CloudFront-to-viewer transfer is cheaper than direct S3 transfer. S3 Lifecycle rules with the 'days since last access' filter automatically transition unwatched videos to Glacier, reducing storage costs by ~68%. Together these address both serving efficiency and archival.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-transition-general-considerations.html"},

{d:D,dn:DN,qt:"single",s:"A DynamoDB table is used for a reporting application that runs queries once a day at 2 AM, processing 10,000 reads. The table is idle the other 23 hours. Currently provisioned at 100 RCUs to handle the batch job. How should the team optimize costs?",
o:["Switch to DynamoDB on-demand capacity mode to pay only for actual reads/writes","Keep provisioned mode but use Auto Scaling with a scheduled scaling action at 2 AM","Reduce provisioned RCUs to 1 and let throttling handle the burst","Export the table to S3 daily and query with Athena instead"],
c:["A"],e:"DynamoDB on-demand mode charges per read/write request with no minimum capacity. For sporadic workloads (one batch job per day), on-demand eliminates the cost of 23 hours of idle provisioned capacity. The 10,000 reads at $0.25 per million reads costs fractions of a cent, versus paying for 100 RCUs continuously ($4.75/day).",df:"Standard",u:"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadWriteCapacityMode.html"},

{d:D,dn:DN,qt:"single",s:"A company runs compute workloads that aren't performance-sensitive but run 24/7. They want to reduce costs by switching from x86 (Intel/AMD) instances to a more cost-effective processor architecture. Which EC2 instance family should they evaluate?",
o:["T3 burstable instances for lower baseline costs","Graviton-based instances (M7g, C7g, R7g) for up to 40% better price-performance than x86","Mac instances for Apple Silicon efficiency","Inf2 instances optimized for inference workloads"],
c:["B"],e:"AWS Graviton processors (ARM-based, custom-designed by AWS) offer up to 40% better price-performance compared to equivalent x86 instances. Graviton instances (identifiable by the 'g' suffix: m7g, c7g, r7g) are ideal for general-purpose, compute-intensive, and memory-intensive workloads. Most Linux-based applications run without modification on ARM.",df:"Standard",u:"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html"},

{d:D,dn:DN,qt:"single",s:"A company has multiple development and testing environments that engineers use only during business hours (8 AM to 6 PM, Monday-Friday). The environments run on EC2 instances and RDS databases. What is the MOST cost-effective approach?",
o:["Use smaller instance types and accept slower performance during off-hours","Implement scheduled scaling with AWS Instance Scheduler to stop instances outside business hours","Migrate all dev/test to Spot Instances that auto-terminate","Use Reserved Instances for all dev/test environments to get discounts"],
c:["B"],e:"AWS Instance Scheduler automates starting and stopping EC2 and RDS instances on a schedule. Stopping dev/test resources outside business hours (14 hours/day weekdays + weekends) reduces compute costs by approximately 70%. Stopped instances incur no compute charges (only EBS storage). Reserved Instances for intermittent use waste money during off-hours.",df:"Standard",u:"https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/welcome.html"},

{d:D,dn:DN,qt:"single",s:"A company needs to reduce cross-region data transfer costs between their application in us-east-1 and a disaster recovery site in eu-west-1. They transfer 10TB of database replication data monthly. Which approach helps reduce these costs?",
o:["Compress data before replication to reduce the volume of transferred bytes","Switch to S3 Transfer Acceleration for faster, cheaper cross-region transfers","Use VPC Peering which eliminates cross-region data transfer charges","Move both regions to the same geographic area to reduce transfer distance"],
c:["A"],e:"Compressing data before cross-region transfer directly reduces the volume of bytes transferred, proportionally reducing data transfer costs. Cross-region transfer is charged per GB ($0.02/GB), so compressing 10TB by 60% saves approximately $120/month. S3 Transfer Acceleration adds cost, doesn't reduce it. VPC peering does NOT eliminate cross-region transfer charges.",df:"Challenging",u:"https://docs.aws.amazon.com/cur/latest/userguide/understanding-your-data-transfer-charges.html"},
];
