// SAA-C03 Domain 2: Design Resilient Architectures (26% weight) — 18 unique questions
const D = "saa-d2", DN = "Domain 2: Design Resilient Architectures";
export default [
{d:D,dn:DN,qt:"single",s:"A company runs a critical e-commerce database on Amazon RDS MySQL. They need the database to automatically failover to a standby replica in another Availability Zone with minimal data loss if the primary fails. Which RDS feature provides this?",
o:["RDS Read Replicas with manual promotion","RDS Multi-AZ deployment with synchronous standby replication","RDS cross-region read replica with asynchronous replication","RDS automated backups with point-in-time recovery"],
c:["B"],e:"RDS Multi-AZ creates a synchronous standby replica in a different AZ. During a failure, RDS automatically promotes the standby to primary with no data loss and a typical failover time of 60-120 seconds. Read replicas use asynchronous replication and require manual promotion.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html"},

{d:D,dn:DN,qt:"single",s:"A microservices architecture has a frontend API that receives bursts of 50,000 requests per second during flash sales. The backend order processing service can only handle 5,000 requests per second. How should the architecture be designed to avoid dropping orders?",
o:["Scale the frontend to match the backend's processing rate using throttling","Place an Amazon SQS queue between the frontend and backend to buffer requests","Deploy the backend on larger EC2 instances to match the frontend throughput","Use Amazon ElastiCache to temporarily store orders and replay them later"],
c:["B"],e:"SQS decouples the fast producer (frontend) from the slow consumer (backend) by buffering messages durably. The backend processes messages at its own pace from the queue. This is the standard pattern for handling traffic spikes without losing data. ElastiCache is a cache, not a durable message buffer.",df:"Standard",u:"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html"},

{d:D,dn:DN,qt:"single",s:"A three-tier web application must maintain availability even if an entire Availability Zone fails. The application tier is stateless. Which architecture provides this resilience?",
o:["Deploy all tiers in a single AZ with automated EBS snapshots for recovery","Deploy an ALB across multiple AZs with Auto Scaling groups spanning at least two AZs","Use a single large EC2 instance with enhanced networking for fast recovery","Deploy in a single AZ and use Route 53 health checks to redirect traffic"],
c:["B"],e:"An ALB distributes traffic across instances in multiple AZs. Auto Scaling ensures the desired capacity is maintained even if one AZ fails by launching replacement instances in healthy AZs. This provides active-active resilience with no manual intervention. Single-AZ deployments are single points of failure.",df:"Standard",u:"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-subnets.html"},

{d:D,dn:DN,qt:"single",s:"A global SaaS company needs their DynamoDB data to be available with single-digit millisecond read latency in US, Europe, and Asia simultaneously, with active write capability in each region. Which feature should they use?",
o:["DynamoDB Streams with Lambda-based cross-region replication","DynamoDB Global Tables for multi-region, multi-active replication","DynamoDB DAX clusters deployed in each region reading from a single-region table","DynamoDB on-demand backup and restore across regions"],
c:["B"],e:"DynamoDB Global Tables provide fully managed multi-region, multi-active replication. Applications can read and write to local table replicas with single-digit millisecond latency. Changes are automatically propagated to all replicas. DAX is a read-through cache for a single table, not cross-region replication.",df:"Standard",u:"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html"},

{d:D,dn:DN,qt:"multiple",s:"A company needs a disaster recovery solution for their primary application in us-east-1 with an RTO of 15 minutes and RPO of 1 minute. They want to minimize costs during normal operations. Which TWO components should be part of their DR strategy? (Select TWO.)",
o:["An Aurora Global Database with a secondary cluster in us-west-2 for sub-minute replication lag","Auto Scaling groups in us-west-2 configured to scale from zero when activated by Route 53 failover","A fully scaled duplicate environment running active-active in us-west-2","Manual AMI copies to us-west-2 performed weekly","Periodic database exports to S3 with cross-region replication"],
c:["A","B"],e:"Aurora Global Database provides cross-region replication with less than 1 second lag (meeting RPO < 1 minute). A warm standby approach with ASGs that can rapidly scale up in the DR region meets the 15-minute RTO. This is more cost-effective than active-active while meeting the requirements. Weekly AMI copies and periodic exports don't meet the RPO.",df:"Challenging",u:"https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database.html"},

{d:D,dn:DN,qt:"single",s:"An application processes messages from SQS but occasionally fails during processing. Messages that fail 3 times should be moved to a separate queue for investigation rather than being retried indefinitely. What should be configured?",
o:["Set the message retention period to 3 minutes","Configure a dead-letter queue (DLQ) with a maximum receive count of 3","Enable long polling with a 3-second timeout","Set the visibility timeout to 3 seconds to force rapid retries"],
c:["B"],e:"A dead-letter queue (DLQ) with maxReceiveCount=3 automatically moves messages that have been received (and not deleted) 3 times to the DLQ. This prevents poison messages from blocking the queue and preserves them for debugging. The visibility timeout controls how long a message is invisible after being read, not retry behavior.",df:"Standard",u:"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html"},

{d:D,dn:DN,qt:"single",s:"A media company stores video assets in S3 and needs them replicated to a different region for disaster recovery. Only new objects uploaded after enabling replication should be replicated. What should they configure?",
o:["S3 Cross-Region Replication (CRR) with versioning enabled on both buckets","Copy all existing objects using aws s3 sync and set up CloudWatch Events for new objects","Enable S3 Transfer Acceleration between the two regions","Configure S3 Batch Operations to periodically copy objects between buckets"],
c:["A"],e:"S3 Cross-Region Replication (CRR) automatically replicates new objects to a destination bucket in another region. Versioning must be enabled on both source and destination buckets. By default, CRR only replicates new objects after the rule is created. Existing objects can be replicated using S3 Batch Replication if needed.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html"},

{d:D,dn:DN,qt:"single",s:"A notification system must send a single event to multiple subscribers — an SQS queue for order processing, a Lambda function for analytics, and an HTTPS endpoint for a partner webhook — simultaneously. Which pattern should be used?",
o:["Publish the event to multiple SQS queues using separate API calls from the application","Use an SNS topic with SQS, Lambda, and HTTPS subscriptions for fan-out","Create a Kinesis Data Stream with multiple consumers","Use EventBridge with a single rule targeting all three destinations"],
c:["B"],e:"SNS fan-out is the standard pattern for broadcasting a single message to multiple subscribers of different types. An SNS topic can have SQS, Lambda, HTTP/S, email, and SMS subscriptions simultaneously. Each subscriber receives a copy of every message independently. This decouples the publisher from subscribers.",df:"Standard",u:"https://docs.aws.amazon.com/sns/latest/dg/sns-common-scenarios.html"},

{d:D,dn:DN,qt:"single",s:"A company needs to protect their RDS database against accidental deletion by an administrator while still allowing normal stop/start/modify operations. Which feature should be enabled?",
o:["Enable RDS automated backups with 35-day retention","Enable RDS deletion protection","Create a read replica to serve as a backup in case of deletion","Take manual snapshots before any administrative operation"],
c:["B"],e:"RDS deletion protection prevents the database instance from being deleted through the console, CLI, or API. An administrator must first disable deletion protection before deleting the instance, providing a two-step safeguard against accidental deletion. Automated backups and snapshots help with data recovery but don't prevent the deletion itself.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_DeleteInstance.html"},

{d:D,dn:DN,qt:"multiple",s:"A company needs to ensure their web application automatically recovers from instance failures and maintains at least 4 healthy instances across 3 AZs at all times. Which TWO configurations are required? (Select TWO.)",
o:["An Auto Scaling group with min=4 spanning 3 AZs with ELB health checks","ALB target group health checks with a custom health check path on the application","CloudWatch alarm to send an email notification when instances fail","A launch template specifying a single specific Availability Zone","Enhanced monitoring enabled on all EC2 instances"],
c:["A","B"],e:"Auto Scaling group with min=4 across 3 AZs automatically replaces unhealthy instances and distributes them across zones. ELB health checks (instead of default EC2 health checks) detect application-level failures, not just instance hardware issues. The custom health check path validates that the application is truly functional, not just that the instance is running.",df:"Standard",u:"https://docs.aws.amazon.com/autoscaling/ec2/userguide/autoscaling-load-balancer.html"},

{d:D,dn:DN,qt:"single",s:"A stateful web application stores user session data in memory on EC2 instances. When Auto Scaling terminates an instance, users lose their session. How should the architecture be modified to maintain session persistence?",
o:["Enable sticky sessions on the ALB to always route users to the same instance","Externalize session storage to Amazon ElastiCache Redis for shared, persistent sessions","Increase the instance size to handle more sessions without scaling","Store session data in EBS volumes and reattach them to new instances"],
c:["B"],e:"Externalizing sessions to ElastiCache Redis makes the application tier truly stateless, allowing any instance to serve any user. Redis provides sub-millisecond access and supports replication for high availability. Sticky sessions create uneven load distribution and sessions are still lost if the sticky instance fails.",df:"Standard",u:"https://docs.aws.amazon.com/elasticache/latest/red-ug/elasticache-use-cases.html"},

{d:D,dn:DN,qt:"single",s:"A company needs to perform a blue/green deployment of their application with the ability to instantly switch traffic from the old version to the new version, and roll back within seconds if issues arise. Which approach is BEST?",
o:["Deploy the new version on separate instances behind a second ALB and use Route 53 weighted routing to shift traffic","Use an ALB with two target groups and swap the listener rule to point to the new target group","Perform a rolling update by replacing instances one at a time in the Auto Scaling group","Use CloudFormation stack updates with UpdatePolicy to replace the entire stack"],
c:["B"],e:"ALB listener rule swapping enables instant blue/green switching. Both old (blue) and new (green) target groups run simultaneously. The ALB listener rule is updated to forward traffic to the green group. Rollback is instant by reverting the listener rule. Route 53 weighted routing introduces DNS TTL delays.",df:"Challenging",u:"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html"},

{d:D,dn:DN,qt:"single",s:"A serverless application uses Lambda functions triggered by API Gateway. Some Lambda functions occasionally time out when connecting to a downstream RDS database due to connection pool exhaustion. What should be implemented to resolve this?",
o:["Increase the Lambda function timeout to 15 minutes","Use Amazon RDS Proxy to pool and manage database connections","Increase the RDS instance size to support more connections","Cache all database responses in Lambda's /tmp directory"],
c:["B"],e:"RDS Proxy manages a pool of database connections, allowing Lambda functions to share connections efficiently. Without RDS Proxy, each Lambda invocation opens a new database connection, quickly exhausting the connection limit under high concurrency. RDS Proxy also handles failover transparently.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html"},

{d:D,dn:DN,qt:"single",s:"A logistics company needs exactly-once processing and strict ordering of messages based on order ID for their shipment tracking system. Which messaging service and configuration should they use?",
o:["SQS Standard queue with deduplication logic in the consumer application","SQS FIFO queue with message group ID set to the order ID","SNS FIFO topic with standard SQS subscription","Kinesis Data Streams with one shard per order"],
c:["B"],e:"SQS FIFO queues provide exactly-once processing and strict ordering within a message group. Setting the message group ID to the order ID ensures all messages for the same order are processed in sequence, while messages for different orders can be processed in parallel. Standard queues offer at-least-once delivery with best-effort ordering.",df:"Standard",u:"https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html"},

{d:D,dn:DN,qt:"single",s:"A company runs an application in a single AWS region. They need to plan for a regional outage with an RTO of 4 hours and RPO of 1 hour while keeping DR costs minimal. Which DR strategy is MOST appropriate?",
o:["Multi-site active-active with full infrastructure in the DR region","Warm standby with scaled-down infrastructure running continuously in the DR region","Pilot light with core services (database replication) running and compute infrastructure ready to provision","Backup and restore with periodic snapshots copied to the DR region"],
c:["C"],e:"Pilot light maintains only the critical core elements (like database replication) running in the DR region. Compute resources are pre-configured (AMIs, launch templates) but not running, keeping costs minimal. During failover, the infrastructure is provisioned and scaled up. This meets a 4-hour RTO and 1-hour RPO. Backup & restore has longer RTO; warm standby costs more.",df:"Challenging",u:"https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.html"},

{d:D,dn:DN,qt:"multiple",s:"A company wants to design a fault-tolerant batch processing pipeline that can handle worker node failures without losing progress on long-running jobs. Which TWO design patterns should be applied? (Select TWO.)",
o:["Use SQS to track individual work items and process them independently on worker instances","Implement checkpointing to S3 so workers can resume from the last saved state after restart","Run all batch processing on a single powerful instance to avoid coordination complexity","Store intermediate results in instance store volumes for maximum I/O performance","Use a synchronous request-response pattern between the scheduler and workers"],
c:["A","B"],e:"SQS-based work distribution ensures that if a worker fails, the unprocessed message becomes visible again for another worker to pick up. Checkpointing to S3 allows workers to save progress and resume from the last checkpoint after a restart, avoiding reprocessing of completed work. Instance store volumes are lost when instances terminate.",df:"Challenging",u:"https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/rel_withstand_component_failures_graceful_degradation.html"},

{d:D,dn:DN,qt:"single",s:"A team is running an application that stores user-uploaded files in Amazon EFS. They need the file system to automatically scale storage capacity and throughput based on usage without provisioning in advance. Which EFS throughput mode should they choose?",
o:["EFS Provisioned Throughput mode with a fixed throughput setting","EFS Bursting Throughput mode which scales with stored data size","EFS Elastic Throughput mode which automatically scales throughput independently of storage","EFS Max I/O performance mode for maximum aggregate throughput"],
c:["C"],e:"EFS Elastic Throughput mode automatically scales throughput up or down based on workload demands, independent of file system size. You pay only for the throughput consumed. Bursting mode scales throughput proportionally to storage size, which may not meet needs for small but throughput-intensive workloads. Max I/O is a performance mode, not a throughput mode.",df:"Standard",u:"https://docs.aws.amazon.com/efs/latest/ug/performance.html"},

{d:D,dn:DN,qt:"single",s:"An event-driven architecture uses multiple AWS services. The team needs to route different types of events (user signups, order completions, inventory updates) from various sources to specific targets based on event content. Which service provides content-based routing of events?",
o:["Amazon SNS with message filtering policies","Amazon EventBridge with event rules and patterns","Amazon SQS with multiple queues","Amazon Kinesis Data Streams with partition keys"],
c:["B"],e:"Amazon EventBridge provides content-based routing through event rules with pattern matching. Rules can match on any field in the event JSON structure and route to specific targets (Lambda, SQS, Step Functions, etc.). SNS message filtering is simpler and limited to message attributes, not body content. EventBridge is the preferred service for event-driven architectures.",df:"Standard",u:"https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events.html"},
];
