// SAA-C03 Domain 1: Design Secure Architectures (30% weight) — 35 unique questions
const D = "saa-d1", DN = "Domain 1: Design Secure Architectures";
export default [
{d:D,dn:DN,qt:"single",s:"A company stores sensitive customer PII in Amazon S3. A compliance audit requires that all objects be encrypted using keys the company fully controls, with the ability to audit key usage. Which approach meets these requirements?",
o:["Enable SSE-S3 default encryption on the bucket","Enable SSE-KMS with a customer managed key (CMK) and enable CloudTrail key-level logging","Encrypt objects client-side using application-level AES and upload via HTTPS","Use S3 Bucket Key with an AWS managed key to reduce KMS costs"],
c:["B"],e:"SSE-KMS with a customer managed CMK gives the company full control over key policies, rotation, and grants. CloudTrail logs every Encrypt/Decrypt API call for auditing. SSE-S3 uses AWS-managed keys without customer control. Client-side encryption works but doesn't leverage AWS-native key audit trails.",df:"Standard",u:"https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html"},

{d:D,dn:DN,qt:"single",s:"An application running on Amazon EC2 must read objects from an S3 bucket and write messages to an SQS queue. The security team requires that no long-term credentials be stored on the instances. What is the MOST secure solution?",
o:["Store IAM user access keys in an encrypted file on the instance","Attach an IAM role with an instance profile granting least-privilege S3 and SQS permissions","Use the root account credentials via environment variables","Generate temporary keys manually using the AWS CLI and store them in Parameter Store"],
c:["B"],e:"IAM instance profiles provide temporary, automatically-rotated credentials to EC2 via the instance metadata service. This eliminates long-term credential management. Using access keys—even encrypted—introduces secret management overhead and security risk.",df:"Standard",u:"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html"},

{d:D,dn:DN,qt:"single",s:"A company wants to restrict access to an S3 bucket so that only resources within a specific VPC can reach it, without routing traffic through the internet. Which combination of actions achieves this?",
o:["Create an S3 interface endpoint and add a bucket policy with aws:SourceVpc condition","Create an S3 gateway VPC endpoint and add a bucket policy with aws:sourceVpce condition","Enable S3 Transfer Acceleration and restrict access to the VPC CIDR range","Configure a NAT Gateway and add a bucket policy restricting to the NAT's Elastic IP"],
c:["B"],e:"An S3 gateway VPC endpoint provides private connectivity to S3 without an internet gateway or NAT. The bucket policy's aws:sourceVpce condition restricts access to traffic originating from the specific VPC endpoint, ensuring private-only access.",df:"Standard",u:"https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html"},

{d:D,dn:DN,qt:"single",s:"An organization with 50 AWS accounts needs to enforce a policy preventing any account from launching EC2 instances outside of eu-west-1 and us-east-1. What is the MOST scalable approach?",
o:["Create an IAM policy in each account denying ec2:RunInstances outside the allowed regions","Apply a Service Control Policy (SCP) in AWS Organizations restricting ec2:RunInstances to the two regions","Use AWS Config rules to detect and terminate non-compliant instances","Configure VPC settings in each account to only allow resources in approved regions"],
c:["B"],e:"SCPs in AWS Organizations provide centralized, preventive guardrails that apply across all member accounts. They cannot be overridden by account-level IAM policies. IAM policies per account don't scale and can be modified by account admins. Config rules are detective, not preventive.",df:"Standard",u:"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html"},

{d:D,dn:DN,qt:"multiple",s:"A web application faces frequent SQL injection and cross-site scripting (XSS) attacks. The company also needs protection against large-scale volumetric DDoS attacks targeting their Application Load Balancer. Which TWO services should be combined? (Select TWO.)",
o:["AWS WAF with managed rule groups for SQL injection and XSS","AWS Shield Advanced for DDoS protection with cost protection","Amazon Inspector for vulnerability scanning","Amazon Macie for data classification","AWS Firewall Manager for cross-account rule management"],
c:["A","B"],e:"AWS WAF protects against application-layer attacks (SQLi, XSS) using managed and custom rule groups. Shield Advanced provides enhanced DDoS protection for ALB, CloudFront, and Route 53, including 24/7 DRT support and cost protection during attacks.",df:"Standard",u:"https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html"},

{d:D,dn:DN,qt:"single",s:"An application must securely store and automatically rotate database credentials every 30 days. Developers should retrieve credentials programmatically without hardcoding them. Which service is BEST suited?",
o:["AWS Systems Manager Parameter Store with SecureString parameters","AWS Secrets Manager with automatic rotation enabled","Store credentials in an encrypted S3 object and read at startup","AWS KMS to encrypt credentials embedded in the application configuration file"],
c:["B"],e:"AWS Secrets Manager is purpose-built for managing secrets like database credentials, API keys, and tokens. It natively supports automatic rotation using Lambda functions, and provides an API for programmatic retrieval. Parameter Store SecureString can store secrets but lacks built-in rotation.",df:"Standard",u:"https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html"},

{d:D,dn:DN,qt:"single",s:"A company must ensure that every AWS API call across all regions and accounts is logged and stored immutably for 7 years to meet regulatory requirements. What is the MOST effective approach?",
o:["Enable CloudTrail in each account individually and store logs in local S3 buckets","Create an organization trail in AWS CloudTrail that logs all accounts to a centralized S3 bucket with Object Lock","Enable VPC Flow Logs across all VPCs and store in CloudWatch Logs","Use AWS Config to record all API-related configuration changes"],
c:["B"],e:"An organization trail in CloudTrail automatically captures API calls across all AWS accounts in the organization. Storing logs in an S3 bucket with Object Lock (compliance mode) ensures immutability. VPC Flow Logs capture network traffic, not API calls. Config records resource state changes, not all API calls.",df:"Challenging",u:"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/creating-trail-organization.html"},

{d:D,dn:DN,qt:"single",s:"A company is building a mobile application that requires user sign-up, sign-in, and social login through Google and Facebook. User data must be stored in DynamoDB with per-user access control. Which service should be used?",
o:["IAM users with programmatic access for each mobile user","Amazon Cognito User Pools for authentication and Identity Pools for authorized AWS access","AWS IAM Identity Center (SSO) with SAML federation","AWS STS AssumeRole with a custom-built token vending machine"],
c:["B"],e:"Cognito User Pools handle sign-up/sign-in and social identity federation (Google, Facebook). Cognito Identity Pools then exchange user pool tokens for temporary AWS credentials scoped with IAM policies, enabling per-user DynamoDB access via fine-grained conditions.",df:"Standard",u:"https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html"},

{d:D,dn:DN,qt:"single",s:"A VPC hosts a private application that must call AWS services (CloudWatch, SNS) without any internet access. The company wants to minimize data transfer costs. What should be implemented?",
o:["Deploy a NAT Gateway in a public subnet to allow outbound internet access","Create VPC interface endpoints (AWS PrivateLink) for CloudWatch and SNS","Set up a VPN connection to route AWS API traffic through the corporate data center","Peer the VPC with the default VPC which has internet access"],
c:["B"],e:"VPC interface endpoints (PrivateLink) create private connections to AWS services within the VPC, eliminating the need for internet access via NAT Gateway. This also reduces data transfer costs since PrivateLink traffic stays on the AWS network. NAT Gateway charges per GB processed.",df:"Standard",u:"https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html"},

{d:D,dn:DN,qt:"multiple",s:"A security team needs to continuously detect unauthorized activity and automatically remediate compliance violations across their AWS environment. Which TWO services working together provide this capability? (Select TWO.)",
o:["Amazon GuardDuty for intelligent threat detection","AWS Config rules with automatic remediation actions via SSM","Amazon Inspector for EC2 vulnerability assessments","AWS Artifact for compliance report downloads","AWS Trusted Advisor for cost optimization checks"],
c:["A","B"],e:"GuardDuty uses ML and threat intelligence to detect unauthorized behavior like unusual API calls, cryptocurrency mining, or compromised credentials. AWS Config rules continuously evaluate resource compliance and can trigger automatic remediation through SSM Automation documents.",df:"Standard",u:"https://docs.aws.amazon.com/guardduty/latest/ug/what-is-guardduty.html"},

{d:D,dn:DN,qt:"single",s:"A development team needs to share an encrypted AMI from Account A with Account B. The AMI is encrypted with a customer managed KMS key. What additional step is required beyond sharing the AMI?",
o:["Re-encrypt the AMI using the default AWS managed key before sharing","Update the KMS key policy in Account A to grant Account B permission to use the key","Copy the AMI to Account B as an unencrypted AMI","Create an identical KMS key in Account B with the same key material"],
c:["B"],e:"When sharing an encrypted AMI cross-account, the KMS key policy must explicitly grant the target account permissions (kms:DescribeKey, kms:CreateGrant, kms:Decrypt, kms:ReEncrypt). Without this, Account B cannot decrypt the AMI's backing EBS snapshots during instance launch.",df:"Challenging",u:"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html"},

{d:D,dn:DN,qt:"single",s:"A Lambda function in a private subnet needs to access an Amazon RDS PostgreSQL database. The security team mandates that the database must not be accessible from the internet. How should this be configured?",
o:["Place RDS in a public subnet and restrict its security group to the Lambda CIDR","Deploy the Lambda function inside the VPC private subnet and configure its security group to allow traffic to the RDS security group","Use RDS Proxy with a public endpoint and IAM authentication","Connect Lambda to RDS using an internet gateway with restrictive NACLs"],
c:["B"],e:"Lambda can be configured to run inside a VPC, connecting to private resources. The Lambda function's security group must allow outbound traffic to the RDS port, and the RDS security group must allow inbound from Lambda's security group. Both resources stay in private subnets, ensuring no internet exposure.",df:"Standard",u:"https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html"},

{d:D,dn:DN,qt:"single",s:"An organization's S3 buckets have been accidentally made public multiple times. Management wants a preventive control that ensures no bucket across the entire organization can ever be made public. What is the BEST approach?",
o:["Enable Amazon Macie on all accounts to detect public bucket access","Apply an SCP denying s3:PutBucketPublicAccessBlock with Block Public Access always ON, plus enable S3 Block Public Access at the account level for all accounts","Use AWS Config auto-remediation to flip buckets back to private after detection","Create an EventBridge rule to detect PutBucketPolicy calls and invoke Lambda to revert them"],
c:["B"],e:"Enabling S3 Block Public Access at the account level prevents any bucket in that account from being made public. An SCP ensures account administrators cannot disable this setting. This is a preventive control. Config remediation and EventBridge rules are detective/reactive approaches that leave a window of exposure.",df:"Challenging",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html"},

{d:D,dn:DN,qt:"single",s:"A company needs to issue free SSL/TLS certificates for their public-facing Application Load Balancer and automatically renew them. Which service should they use?",
o:["Purchase certificates from a third-party CA and manually install them on the ALB","Use AWS Certificate Manager (ACM) to provision and manage public certificates","Generate self-signed certificates using OpenSSL and upload to IAM","Use AWS Private CA to issue public-facing certificates"],
c:["B"],e:"AWS Certificate Manager (ACM) provides free public SSL/TLS certificates that integrate directly with ALB, CloudFront, and API Gateway. ACM handles automatic renewal. AWS Private CA is for internal/private certificates and incurs charges. Self-signed certificates cause browser warnings.",df:"Standard",u:"https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html"},

{d:D,dn:DN,qt:"multiple",s:"A healthcare application must encrypt all data in transit between the client and the server, and encrypt all data at rest in S3. Which TWO configurations satisfy both requirements? (Select TWO.)",
o:["Configure the ALB listener to use HTTPS with an ACM certificate for transit encryption","Enable SSE-KMS on the S3 bucket for at-rest encryption with audit capability","Enable S3 Transfer Acceleration to speed up encrypted uploads","Attach a security group to S3 to enforce encrypted connections","Use CloudFront signed URLs to enforce encrypted file downloads"],
c:["A","B"],e:"HTTPS on the ALB (via ACM certificate) encrypts data in transit between client and server using TLS. SSE-KMS on S3 encrypts stored objects with KMS-managed keys and provides CloudTrail audit logs of key usage. Transfer Acceleration improves speed but doesn't provide encryption. S3 doesn't support security groups.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingEncryption.html"},

{d:D,dn:DN,qt:"single",s:"A VPC has public and private subnets. The security team wants to allow inbound HTTP/HTTPS traffic to the public subnet but deny all other inbound traffic. They also want to log all denied traffic for forensic analysis. Which combination of controls should be used?",
o:["Configure security groups to allow HTTP/HTTPS and enable VPC Flow Logs","Configure NACLs to allow inbound HTTP/HTTPS and deny all else, combined with VPC Flow Logs set to capture REJECT traffic","Use AWS Network Firewall stateful rules with alert logging","Configure a web application firewall on each EC2 instance"],
c:["B"],e:"NACLs provide subnet-level stateless filtering and can explicitly deny traffic. VPC Flow Logs with REJECT filter capture all denied network flows for forensic analysis. Security groups cannot explicitly deny traffic and don't log denials. Network Firewall is more complex than needed for simple port filtering.",df:"Standard",u:"https://docs.aws.amazon.com/vpc/latest/userguide/vpc-network-acls.html"},

{d:D,dn:DN,qt:"single",s:"A company needs to discover and classify sensitive data like credit card numbers and personal information stored across hundreds of S3 buckets. Which service should they use?",
o:["AWS Inspector to scan S3 objects for vulnerabilities","Amazon Macie to automatically discover and classify sensitive data in S3","AWS Config to evaluate S3 bucket configurations","Amazon Comprehend to perform NLP analysis on stored documents"],
c:["B"],e:"Amazon Macie uses machine learning and pattern matching to discover, classify, and protect sensitive data (PII, financial data, credentials) stored in Amazon S3. Inspector scans EC2 and container vulnerabilities, not S3 data content. Config evaluates resource configuration compliance, not data content.",df:"Standard",u:"https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html"},

{d:D,dn:DN,qt:"single",s:"A company has a regulatory requirement that encryption keys must never leave a hardware security module and must be under their exclusive control. They need FIPS 140-2 Level 3 validated key storage. Which service meets this requirement?",
o:["AWS KMS with customer managed keys","AWS CloudHSM providing dedicated single-tenant HSM instances","AWS Secrets Manager with encryption enabled","Server-side encryption with S3-managed keys (SSE-S3)"],
c:["B"],e:"AWS CloudHSM provides dedicated, single-tenant FIPS 140-2 Level 3 validated hardware security modules. Keys never leave the HSM boundary and the customer has exclusive control. KMS uses shared multi-tenant HSMs (FIPS 140-2 Level 2) where AWS manages the HSM infrastructure.",df:"Challenging",u:"https://docs.aws.amazon.com/cloudhsm/latest/userguide/introduction.html"},

{d:D,dn:DN,qt:"single",s:"An application needs to call APIs in a partner's AWS account. The partner provides an IAM role ARN with an external ID. How should the application securely obtain credentials to access the partner's resources?",
o:["Request the partner to create IAM user credentials and embed them in the application","Use AWS STS AssumeRole with the partner's role ARN and the provided external ID","Configure VPC peering between both accounts for direct network access","Use AWS Resource Access Manager (RAM) to share resources directly"],
c:["B"],e:"STS AssumeRole enables secure cross-account access by exchanging the calling identity for temporary credentials scoped to the partner's role. The external ID prevents the 'confused deputy' problem by ensuring only authorized callers can assume the role. This avoids long-term credential sharing.",df:"Standard",u:"https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_third-party.html"},

{d:D,dn:DN,qt:"multiple",s:"A company wants to allow developers to create any IAM resource but prevent them from escalating their own privileges beyond a defined boundary. Which TWO mechanisms should be used together? (Select TWO.)",
o:["IAM permissions boundaries to set the maximum permissions developers can grant","An SCP requiring that all created roles include the permissions boundary","AWS CloudTrail to log all IAM API calls for post-event review","IAM Access Analyzer to detect overly permissive policies","Amazon Detective to investigate privilege escalation patterns"],
c:["A","B"],e:"Permissions boundaries define the maximum permissions an IAM entity can have, regardless of identity-based policies. The SCP ensures that any role or user created by developers must attach the boundary, preventing them from creating entities with broader permissions than allowed.",df:"Challenging",u:"https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html"},
];
