// SAA-C03 Domain 3: Design High-Performing Architectures (24% weight) — 17 unique questions
const D = "saa-d3", DN = "Domain 3: Design High-Performing Architectures";
export default [
{d:D,dn:DN,qt:"single",s:"A news website serves millions of readers globally. Static assets (images, CSS, JavaScript) are stored in S3 and account for 80% of requests. Users in Asia and Europe report slow page load times. What should be implemented to reduce latency for all regions?",
o:["Enable S3 Transfer Acceleration on the bucket","Place an Amazon CloudFront distribution in front of the S3 bucket with edge caching","Deploy S3 buckets in each region and use Route 53 latency-based routing","Increase the S3 bucket's request rate by prefixing object keys with random characters"],
c:["B"],e:"CloudFront caches content at 450+ edge locations worldwide, serving requests from the location nearest to the user. For static content, this dramatically reduces latency compared to fetching directly from S3 in a single region. Transfer Acceleration improves upload speed to S3, not download speed to end users.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html"},

{d:D,dn:DN,qt:"single",s:"An application performs the same 10 complex database queries repeatedly, with results changing only once per hour. The RDS PostgreSQL database is under heavy read load. What is the MOST effective way to reduce database load and improve response times?",
o:["Add RDS Read Replicas and distribute queries across them","Implement Amazon ElastiCache Redis to cache query results with a 1-hour TTL","Upgrade the RDS instance to a larger instance class","Enable RDS Performance Insights to identify and optimize slow queries"],
c:["B"],e:"ElastiCache Redis caching eliminates redundant database queries by storing results in-memory with sub-millisecond latency. A 1-hour TTL matches the data refresh rate. Read Replicas help distribute load but still execute the same queries. Performance Insights helps identify bottlenecks but doesn't cache results.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Strategies.html"},

{d:D,dn:DN,qt:"single",s:"A data analytics team runs Apache Spark jobs that require high-throughput sequential reads of large files (50GB+). The jobs are throughput-sensitive, not IOPS-sensitive. Which EBS volume type offers the best price-performance for this workload?",
o:["gp3 (General Purpose SSD) for balanced performance","io2 Block Express for maximum IOPS","st1 (Throughput Optimized HDD) for high-throughput sequential workloads","sc1 (Cold HDD) for the lowest storage cost"],
c:["C"],e:"st1 volumes are designed for large sequential workloads like data warehousing, log processing, and big data analytics. They deliver up to 500 MB/s throughput at a lower cost than SSD volumes. gp3 and io2 are optimized for random IOPS. sc1 has lower throughput and is designed for infrequently accessed data.",df:"Standard",u:"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html"},

{d:D,dn:DN,qt:"single",s:"A gaming application uses DynamoDB to store player profiles. Read latency averages 5ms, but the game requires sub-millisecond read latency for leaderboard queries during tournaments. How should the architecture be optimized?",
o:["Enable DynamoDB Auto Scaling to increase read capacity during tournaments","Add a DynamoDB Accelerator (DAX) cluster in front of the table","Create a Global Secondary Index optimized for leaderboard queries","Switch from DynamoDB to Amazon ElastiCache Redis for all game data"],
c:["B"],e:"DynamoDB Accelerator (DAX) is a fully managed, in-memory cache purpose-built for DynamoDB. It reduces read latency from single-digit milliseconds to microseconds. DAX is API-compatible with DynamoDB, requiring minimal code changes. Auto Scaling adjusts capacity but doesn't reduce latency. GSIs improve query flexibility but not latency.",df:"Standard",u:"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html"},

{d:D,dn:DN,qt:"multiple",s:"A company needs to build a real-time dashboard that processes and visualizes clickstream data from their website. The data arrives at 100,000 events per second during peak hours. Which TWO services should form the core of the data ingestion and processing pipeline? (Select TWO.)",
o:["Amazon Kinesis Data Streams for real-time data ingestion at scale","Amazon Managed Service for Apache Flink (Kinesis Data Analytics) for real-time stream processing","Amazon SQS Standard queue for buffering clickstream events","AWS Batch for processing large volumes of event data","Amazon S3 with event notifications for processing uploaded files"],
c:["A","B"],e:"Kinesis Data Streams handles real-time ingestion of high-volume streaming data (up to millions of records per second). Managed Apache Flink processes the stream in real-time with SQL or Java/Python applications for windowed aggregations, filtering, and enrichment. SQS is message-oriented, not optimized for streaming analytics. AWS Batch is for batch processing.",df:"Standard",u:"https://docs.aws.amazon.com/streams/latest/dev/introduction.html"},

{d:D,dn:DN,qt:"single",s:"A machine learning team needs a high-performance shared file system for training jobs running on a cluster of EC2 GPU instances. The workload requires sub-millisecond latency and hundreds of GB/s throughput for reading training data from S3. Which storage solution is BEST?",
o:["Amazon EFS with Provisioned Throughput mode","Amazon FSx for Lustre linked to the S3 training data bucket","An NFS server running on a large EC2 instance with instance store volumes","Amazon S3 with multipart download optimization"],
c:["B"],e:"FSx for Lustre is a high-performance parallel file system designed for compute-intensive workloads like ML training. It integrates natively with S3, lazily loading data as needed. It provides sub-millisecond latencies and hundreds of GB/s throughput. EFS is POSIX-compliant but doesn't match Lustre's HPC-grade throughput.",df:"Challenging",u:"https://docs.aws.amazon.com/fsx/latest/LustreGuide/what-is.html"},

{d:D,dn:DN,qt:"single",s:"A company has hundreds of Lambda functions connecting to an RDS MySQL database. During traffic spikes, the database reaches its maximum connection limit (1,000 connections) and new Lambda invocations fail. What is the recommended solution?",
o:["Increase the max_connections parameter on the RDS instance","Place Amazon RDS Proxy between Lambda and the database to pool connections","Use ElastiCache as a write-through cache to reduce database connections","Switch from RDS MySQL to DynamoDB to eliminate connection limits"],
c:["B"],e:"RDS Proxy maintains a pool of established database connections that Lambda functions share. Instead of each Lambda invocation opening a new connection, RDS Proxy multiplexes thousands of concurrent Lambda connections into a smaller pool of database connections. This prevents connection exhaustion during traffic spikes.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html"},

{d:D,dn:DN,qt:"single",s:"A financial trading platform requires the lowest possible network latency between EC2 instances in a cluster that perform high-frequency inter-node communication. Which EC2 placement strategy should be used?",
o:["Spread placement group to maximize hardware isolation","Partition placement group to reduce correlated failures","Cluster placement group to pack instances physically close together","Default placement to let AWS optimize for availability"],
c:["C"],e:"Cluster placement groups place instances in a single Availability Zone on the same underlying hardware rack, providing the lowest network latency and highest network throughput between instances (up to 100 Gbps with enhanced networking). Spread groups maximize isolation. Partition groups reduce correlated failures for distributed systems like HDFS/Kafka.",df:"Standard",u:"https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html"},

{d:D,dn:DN,qt:"multiple",s:"A company wants to optimize the performance of their REST API served by API Gateway and Lambda. The API serves mostly read-heavy GET requests where responses don't change frequently. Which TWO optimizations would reduce latency and backend load? (Select TWO.)",
o:["Enable API Gateway response caching with appropriate TTL values","Use Lambda Provisioned Concurrency to eliminate cold start latency","Switch from REST API to HTTP API for lower Gateway overhead","Increase Lambda memory allocation to 10GB for every function","Enable API Gateway request validation to reject invalid requests early"],
c:["A","B"],e:"API Gateway caching stores responses at the gateway layer, serving repeated identical requests without invoking Lambda. This reduces both latency and cost for read-heavy APIs. Provisioned Concurrency keeps Lambda functions initialized and warm, eliminating cold start delays (which can add 1-10 seconds for VPC-connected functions). Both directly address read-heavy API performance.",df:"Standard",u:"https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-caching.html"},

{d:D,dn:DN,qt:"single",s:"Users uploading large video files (2-10GB) from South America to an S3 bucket in us-east-1 experience very slow upload speeds due to geographic distance. What is the MOST effective way to accelerate these uploads?",
o:["Enable S3 Transfer Acceleration on the bucket to route uploads through CloudFront edge locations","Increase the S3 bucket's provisioned throughput capacity","Create a VPN connection between South America and the us-east-1 region","Use S3 multipart upload with larger part sizes to improve throughput"],
c:["A"],e:"S3 Transfer Acceleration uses CloudFront's globally distributed edge locations to accelerate uploads. Data is ingested at the nearest edge location and transferred to S3 over AWS's optimized backbone network, significantly improving speed for long-distance transfers. Multipart upload enables parallel upload of parts but doesn't address network path optimization.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html"},

{d:D,dn:DN,qt:"single",s:"A company runs a TCP-based gaming server that must serve players globally with the lowest possible latency. The server runs on EC2 instances in us-west-2 and eu-west-1. DNS-based routing adds latency due to DNS resolution times. What should be used instead?",
o:["Route 53 with latency-based routing policy","AWS Global Accelerator with endpoints in both regions","CloudFront with custom origin configurations","A Network Load Balancer with cross-region target groups"],
c:["B"],e:"AWS Global Accelerator uses Anycast IP addresses that route traffic over the AWS global network to the optimal regional endpoint. Unlike DNS-based routing, it doesn't depend on DNS resolution or TTL caching. It provides deterministic routing and improves TCP performance by up to 60% compared to the public internet. CloudFront is for HTTP/HTTPS content, not arbitrary TCP.",df:"Standard",u:"https://docs.aws.amazon.com/global-accelerator/latest/dg/what-is-global-accelerator.html"},

{d:D,dn:DN,qt:"single",s:"A company needs to run lightweight request transformations (URL rewrites, header manipulation, A/B testing) at CloudFront edge locations with sub-millisecond execution time. Which compute option is MOST appropriate?",
o:["Lambda@Edge functions triggered by CloudFront events","CloudFront Functions for lightweight, short-running edge computations","An origin-side Lambda function behind API Gateway","A fleet of EC2 instances deployed in every AWS region"],
c:["B"],e:"CloudFront Functions run at CloudFront edge locations with sub-millisecond startup time and support up to millions of requests per second. They're designed for lightweight transformations like URL rewrites, header manipulation, cache key normalization, and simple A/B testing. Lambda@Edge is more powerful but has higher latency and cost.",df:"Standard",u:"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html"},

{d:D,dn:DN,qt:"single",s:"A data warehouse team needs to run complex analytical SQL queries across petabytes of structured data with fast query performance and the ability to scale compute independently of storage. Which AWS service is BEST suited?",
o:["Amazon RDS PostgreSQL with read replicas for parallel query execution","Amazon Redshift with RA3 nodes for managed columnar storage with independent compute scaling","Amazon Athena for serverless queries directly on S3 data","Amazon Aurora PostgreSQL with parallel query enabled"],
c:["B"],e:"Amazon Redshift is purpose-built for data warehousing with columnar storage, massively parallel processing (MPP), and result caching. RA3 nodes separate compute and storage, allowing independent scaling. Athena is serverless SQL on S3 but is optimized for ad-hoc queries, not sustained complex analytics. Aurora is OLTP, not OLAP.",df:"Standard",u:"https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html"},

{d:D,dn:DN,qt:"single",s:"An application needs to serve structured product catalog data with sub-millisecond read latency, automatic scaling, and no operational overhead for capacity planning. The access patterns are well-defined key-value lookups. Which database is BEST suited?",
o:["Amazon RDS MySQL with ElastiCache for caching","Amazon DynamoDB in on-demand capacity mode","Amazon DocumentDB for flexible schema queries","Amazon Neptune for relationship-heavy data traversals"],
c:["B"],e:"DynamoDB in on-demand mode provides single-digit millisecond performance at any scale with no capacity planning. It automatically scales read/write capacity based on traffic patterns. For well-defined key-value access patterns, DynamoDB is optimal. RDS with ElastiCache adds operational complexity. DocumentDB and Neptune are for different access patterns.",df:"Standard",u:"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.html"},

{d:D,dn:DN,qt:"single",s:"A team needs to query and analyze data stored in S3 in Parquet format using standard SQL without setting up any infrastructure. They run ad-hoc queries a few times per week. Which service provides the most cost-effective solution?",
o:["Amazon EMR with Hive for SQL-on-Hadoop queries","Amazon Athena for serverless, pay-per-query SQL on S3","Load the data into Amazon Redshift for optimized query performance","Use Amazon RDS with the S3 import feature to load data for querying"],
c:["B"],e:"Amazon Athena is serverless — no infrastructure to manage — and charges only per TB of data scanned. It works directly on S3 data in formats like Parquet, ORC, CSV, and JSON. Parquet's columnar format works especially well with Athena since it enables column pruning to reduce scanned data. For infrequent queries, pay-per-query is far more cost-effective than provisioned services.",df:"Standard",u:"https://docs.aws.amazon.com/athena/latest/ug/what-is.html"},

{d:D,dn:DN,qt:"multiple",s:"A content delivery architecture serves dynamic API responses and static assets. The team wants to optimize performance by caching static assets at the edge while ensuring dynamic API requests always reach the origin. Which TWO CloudFront configurations achieve this? (Select TWO.)",
o:["Configure cache behaviors with long TTL for static asset paths (/static/*, /images/*)","Set the default cache behavior to forward all headers for dynamic API paths, disabling caching","Enable Origin Shield to reduce load on the origin server","Use signed URLs for all content to prevent unauthorized caching","Enable field-level encryption for all cached responses"],
c:["A","B"],e:"CloudFront cache behaviors allow different caching rules per URL path pattern. Static asset paths get long TTLs for edge caching, while dynamic API paths forward all headers (which effectively disables caching since each unique header set creates a different cache key). This gives you edge performance for static content and fresh responses for dynamic requests.",df:"Challenging",u:"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html"},

{d:D,dn:DN,qt:"single",s:"An e-commerce platform needs full-text search across millions of product listings with faceted filtering, fuzzy matching, and auto-suggestions. The search must return results within 100ms. Which AWS service should be used?",
o:["DynamoDB with scan operations and filter expressions","Amazon OpenSearch Service with relevant index mappings and search templates","Amazon RDS with PostgreSQL full-text search indexes","Amazon CloudSearch for managed search domains"],
c:["B"],e:"Amazon OpenSearch Service (successor to Elasticsearch Service) is purpose-built for full-text search, log analytics, and real-time monitoring. It supports fuzzy matching, faceted search, autocomplete suggestions, and relevance tuning. DynamoDB Scan operations are expensive and slow for full-text search. RDS full-text search doesn't scale as well for complex search requirements.",df:"Standard",u:"https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html"},
];
