const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, '../src/data');

// Ensure directories exist
['dva-c02', 'dea-c01'].forEach(exam => {
  const dir = path.join(baseDir, exam);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
});

// Comprehensive scenario templates for DVA-C02 (Developer Associate)
const dvaTopics = [
  {
    domainId: 'dva-d1',
    domainName: 'Domain 1: Development with AWS Services',
    scenarios: [
      {
        scenario: "A developer is writing an AWS Lambda function in Node.js to read events from an Amazon Kinesis Data Stream. The function fails to process a record due to a malformed payload. How should the developer configure the event source mapping to handle poison pill records without blocking the entire stream shard?",
        options: [
          { id: "A", text: "Configure a Dead-Letter Queue (DLQ) or On-Failure Destination on the event source mapping and set Maximum Record Age." },
          { id: "B", text: "Increase the Kinesis Shard count by 100." },
          { id: "C", text: "Throw an unhandled JavaScript exception to stop Kinesis processing." },
          { id: "D", text: "Set Lambda Reserved Concurrency to 0." }
        ],
        correct: ["A"],
        explanation: "Lambda Kinesis event source mappings support Destination on Failure, Maximum Record Age, and Bisect Batch on Function Error settings to isolate poison pill records into SQS/SNS without blocking stream progress.",
        awsDocUrl: "https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis.html"
      },
      {
        scenario: "A developer is building a serverless e-commerce application using Amazon DynamoDB. The application needs to update a customer's account balance and record a transaction item atomically in a single request. Which DynamoDB API operation should be used?",
        options: [
          { id: "A", text: "BatchWriteItem" },
          { id: "B", text: "TransactWriteItems" },
          { id: "C", text: "PutItem with conditional expressions" },
          { id: "D", text: "ExecuteStatement with SQL JOIN" }
        ],
        correct: ["B"],
        explanation: "TransactWriteItems allows developers to execute atomic write operations across multiple items within and across DynamoDB tables in an all-or-nothing transaction.",
        awsDocUrl: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transactions.html"
      },
      {
        scenario: "An application hosted on AWS Elastic Beanstalk requires environment properties for database connections. How should the developer securely pass environment variables to Elastic Beanstalk applications without hardcoding them in source code?",
        options: [
          { id: "A", text: "Use Beanstalk Environment Properties or .ebextensions configuration files referencing SSM Parameter Store." },
          { id: "B", text: "Hardcode credentials in the application's package.json." },
          { id: "C", text: "Embed credentials directly in public git commits." },
          { id: "D", text: "Store plaintext credentials in EC2 user data scripts." }
        ],
        correct: ["A"],
        explanation: "Elastic Beanstalk Environment Properties combined with AWS Systems Manager Parameter Store or Secrets Manager allow secure credential injection at runtime.",
        awsDocUrl: "https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-softwaresettings.html"
      }
    ]
  },
  {
    domainId: 'dva-d2',
    domainName: 'Domain 2: Security',
    scenarios: [
      {
        scenario: "A developer is configuring Amazon API Gateway with an AWS Lambda Authorizer. The authorizer validates incoming Bearer JWT tokens. Which IAM policy statement structure must the Lambda authorizer return to API Gateway to grant access to the requested API endpoint?",
        codeSnippet: "{\n  \"principalId\": \"user123\",\n  \"policyDocument\": {\n    \"Version\": \"2012-10-17\",\n    \"Statement\": [{\n      \"Action\": \"execute-api:Invoke\",\n      \"Effect\": \"Allow\",\n      \"Resource\": \"arn:aws:execute-api:region:account-id:api-id/stage/METHOD/path\"\n    }]\n  }\n}",
        options: [
          { id: "A", text: "Return an HTTP 200 status code with a plaintext token payload." },
          { id: "B", text: "Return an IAM policy document specifying Effect: Allow for execute-api:Invoke on the API resource ARN." },
          { id: "C", text: "Return a Signed URL generated by KMS." },
          { id: "D", text: "Return an S3 bucket policy with public read permissions." }
        ],
        correct: ["B"],
        explanation: "An API Gateway Lambda Authorizer must return an IAM policy document containing a principalId and a PolicyDocument authorizing execute-api:Invoke for the target route.",
        awsDocUrl: "https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html"
      },
      {
        scenario: "A web application requires user sign-up, sign-in, and multi-factor authentication (MFA). The application needs to issue OAuth 2.0 access and ID tokens upon successful authentication. Which AWS service provides these capabilities natively?",
        options: [
          { id: "A", text: "Amazon Cognito User Pools" },
          { id: "B", text: "AWS IAM Identity Center" },
          { id: "C", text: "Amazon Cognito Identity Pools (Federated Identities)" },
          { id: "D", text: "AWS Key Management Service (AWS KMS)" }
        ],
        correct: ["A"],
        explanation: "Amazon Cognito User Pools serve as a user directory providing sign-up, sign-in, MFA, and OAuth 2.0 JWT token generation for web and mobile applications.",
        awsDocUrl: "https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html"
      }
    ]
  },
  {
    domainId: 'dva-d3',
    domainName: 'Domain 3: Deployment',
    scenarios: [
      {
        scenario: "A developer is defining serverless infrastructure using AWS SAM (Serverless Application Model). The SAM template needs to provision an AWS Lambda function, an Amazon API Gateway, and an Amazon DynamoDB table. Which resource type in SAM represents a serverless function with built-in event triggers?",
        options: [
          { id: "A", text: "AWS::Serverless::Function" },
          { id: "B", text: "AWS::Lambda::Function" },
          { id: "C", text: "AWS::EC2::Instance" },
          { id: "D", text: "AWS::CloudFormation::Stack" }
        ],
        correct: ["A"],
        explanation: "AWS::Serverless::Function is the SAM resource type that simplifies Lambda definition, automatically provisioning execution roles and event source integrations.",
        awsDocUrl: "https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html"
      },
      {
        scenario: "A microservice container application runs on AWS Fargate. The developer wants to update the container image with zero downtime using Amazon ECS deployment types. Which deployment strategy gradually shifts traffic using AWS CodeDeploy?",
        options: [
          { id: "A", text: "Blue/green deployment with CodeDeploy" },
          { id: "B", text: "In-place rolling deployment with 0% minimum healthy percent" },
          { id: "C", text: "Recreate deployment with full cluster shutdown" },
          { id: "D", text: "Manual DNS A-record swap" }
        ],
        correct: ["A"],
        explanation: "ECS blue/green deployments powered by CodeDeploy allow new container tasks to be provisioned and verified before shifting production traffic smoothly through an Application Load Balancer target group.",
        awsDocUrl: "https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-blue-green.html"
      }
    ]
  },
  {
    domainId: 'dva-d4',
    domainName: 'Domain 4: Refactoring, Troubleshooting and Optimization',
    scenarios: [
      {
        scenario: "A developer is inspecting slow AWS Lambda execution times. Tracing shows that cold starts take up to 4 seconds due to heavy SDK initialization code outside the handler function. Which action should the developer take to reduce cold start latency for critical production requests?",
        options: [
          { id: "A", text: "Configure Provisioned Concurrency for the Lambda function." },
          { id: "B", text: "Increase function memory allocation to 10,240 MB." },
          { id: "C", text: "Move initialization code into the Lambda handler function body." },
          { id: "D", text: "Switch from Node.js runtime to Java 17 runtime." }
        ],
        correct: ["A"],
        explanation: "Provisioned Concurrency keeps Lambda instances initialized and hyper-warmed, eliminating cold start latency for critical production endpoints.",
        awsDocUrl: "https://docs.aws.amazon.com/lambda/latest/dg/provisioned-concurrency.html"
      }
    ]
  }
];

// Comprehensive scenario templates for DEA-C01 (Data Engineer Associate)
const deaTopics = [
  {
    domainId: 'dea-d1',
    domainName: 'Domain 1: Data Ingestion and Processing',
    scenarios: [
      {
        scenario: "A data engineer needs to stream financial transaction records into Amazon Redshift with less than 60 seconds latency. The solution must handle dynamic scaling without managing underlying server clusters. Which AWS pipeline architecture satisfies these requirements?",
        options: [
          { id: "A", text: "Amazon Kinesis Data Streams -> Amazon Kinesis Data Firehose -> Amazon Redshift with auto-COPY command." },
          { id: "B", text: "AWS Snowball Edge physical ship device daily." },
          { id: "C", text: "AWS Glue batch job running once every 24 hours." },
          { id: "D", text: "Amazon S3 Glacier Select queries." }
        ],
        correct: ["A"],
        explanation: "Kinesis Data Streams coupled with Kinesis Data Firehose provides serverless, continuous streaming ingestion into Amazon Redshift via automated S3 intermediate buffering and COPY command execution.",
        awsDocUrl: "https://docs.aws.amazon.com/firehose/latest/dev/about-delivering-redshift.html"
      },
      {
        scenario: "A data processing pipeline uses Apache Spark on Amazon EMR to transform 50 TB of JSON logs daily. The cost of running persistent EMR instances is too high. What strategy reduces EMR infrastructure costs while maintaining task resilience?",
        options: [
          { id: "A", text: "Use On-Demand instances for Primary (Master) and Core nodes, and Spot Instances for Task nodes." },
          { id: "B", text: "Use Spot Instances for Master nodes only." },
          { id: "C", text: "Migrate EMR data processing to Amazon RDS single-AZ." },
          { id: "D", text: "Run Spark scripts on AWS Lambda 15-minute executions." }
        ],
        correct: ["A"],
        explanation: "Using On-Demand instances for Master/Core nodes guarantees cluster stability and HDFS state, while using Spot instances for stateless Task nodes drastically reduces compute costs.",
        awsDocUrl: "https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-instances-guidelines.html"
      }
    ]
  },
  {
    domainId: 'dea-d2',
    domainName: 'Domain 2: Data Store Management',
    scenarios: [
      {
        scenario: "A data engineer is designing an Amazon S3 data lake structure for analytical workloads queried by Amazon Athena. The incoming data consists of hourly sales records. How should the S3 bucket prefixes be formatted to optimize query performance and cut Athena scanning costs?",
        options: [
          { id: "A", text: "s3://my-datalake/sales/year=YYYY/month=MM/day=DD/" },
          { id: "B", text: "s3://my-datalake/all_sales_files_in_root/" },
          { id: "C", text: "s3://my-datalake/sales_YYYYMMDD_randomhash/" },
          { id: "D", text: "s3://my-datalake/sales.zip" }
        ],
        correct: ["A"],
        explanation: "Using Apache Hive style partitioning (year=YYYY/month=MM/day=DD/) allows Athena to perform partition pruning, scanning only the necessary S3 prefixes and cutting query costs significantly.",
        awsDocUrl: "https://docs.aws.amazon.com/athena/latest/ug/partitions.html"
      }
    ]
  },
  {
    domainId: 'dea-d3',
    domainName: 'Domain 3: Data Operations and Support',
    scenarios: [
      {
        scenario: "A data team uses AWS Step Functions to orchestrate a complex ETL workflow consisting of AWS Glue jobs, Lambda functions, and EMR clusters. How can the team ensure that failed state machine executions automatically notify the DevOps team via Slack/SNS?",
        options: [
          { id: "A", text: "Configure an Amazon EventBridge rule filtering Step Functions Execution Status Change events for FAILED status, pointing to an Amazon SNS topic." },
          { id: "B", text: "Poll the Step Functions API manually using a bash script." },
          { id: "C", text: "Store logs in S3 Glacier." },
          { id: "D", text: "Re-run the state machine every minute continuously." }
        ],
        correct: ["A"],
        explanation: "Amazon EventBridge natively captures AWS Step Functions execution state changes (SUCCEEDED, FAILED, TIMED_OUT) and triggers SNS topics for immediate incident notifications.",
        awsDocUrl: "https://docs.aws.amazon.com/step-functions/latest/dg/cw-events.html"
      }
    ]
  },
  {
    domainId: 'dea-d4',
    domainName: 'Domain 4: Data Security and Governance',
    scenarios: [
      {
        scenario: "A company stores sensitive PII data (Personally Identifiable Information) in an S3 Data Lake. The compliance team requires automatic identification and notification whenever unencrypted PII like credit card numbers or SSNs are uploaded. Which service meets this requirement?",
        options: [
          { id: "A", text: "Amazon Macie" },
          { id: "B", text: "AWS KMS" },
          { id: "C", text: "AWS Shield Advanced" },
          { id: "D", text: "Amazon Inspector" }
        ],
        correct: ["A"],
        explanation: "Amazon Macie is a fully managed data security and privacy service that uses machine learning and pattern matching to automatically discover, classify, and protect sensitive PII data in S3.",
        awsDocUrl: "https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html"
      }
    ]
  }
];

// Generate sets 1-10 for DVA-C02 (65 questions per set: 50 Scored, 15 Unscored Beta)
for (let setNum = 1; setNum <= 10; setNum++) {
  const questions = [];
  
  for (let i = 1; i <= 65; i++) {
    const isScored = i <= 50; // 50 Scored Questions, 15 Unscored (Beta)
    const isMultiple = (i % 5 === 0); // Every 5th question is multiple choice
    const topicIdx = (i + setNum) % dvaTopics.length;
    const topic = dvaTopics[topicIdx];
    const item = topic.scenarios[(i + setNum) % topic.scenarios.length];

    if (isMultiple) {
      questions.push({
        id: `dva-${setNum}-${i}`,
        setId: setNum,
        examCode: "DVA-C02",
        domainId: topic.domainId,
        domainName: topic.domainName,
        questionType: "multiple",
        selectCount: 2,
        isScored,
        scenario: `[DVA-C02 Set ${setNum} - Q${i}] A company is building a highly resilient serverless web application using AWS Lambda, Amazon API Gateway, and Amazon DynamoDB. Which TWO security and architectural patterns should the developer implement to secure the API and prevent unauthorized access?`,
        options: [
          { id: "A", text: "Enable AWS WAF web ACL on API Gateway stages to block SQL injection and cross-site scripting (XSS) attacks." },
          { id: "B", text: "Use Amazon Cognito User Pools authorizers or custom Lambda authorizers to validate OAuth 2.0 JWT tokens." },
          { id: "C", text: "Store database credentials as hardcoded strings inside Lambda function source code." },
          { id: "D", text: "Disable CORS on API Gateway to allow requests from any origin." },
          { id: "E", text: "Grant full AdministratorAccess to the Lambda execution role." }
        ],
        correctAnswer: ["A", "B"],
        explanation: "Integrating AWS WAF with API Gateway provides layer 7 protection against common web exploits, while Cognito User Pool authorizers validate JWT tokens before invoking Lambda execution logic.",
        awsDocUrl: "https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-aws-waf.html",
        difficulty: i > 40 ? "Complex" : "Standard"
      });
    } else {
      questions.push({
        id: `dva-${setNum}-${i}`,
        setId: setNum,
        examCode: "DVA-C02",
        domainId: topic.domainId,
        domainName: topic.domainName,
        questionType: "single",
        isScored,
        scenario: `[DVA-C02 Set ${setNum} - Q${i}] ${item.scenario}`,
        codeSnippet: item.codeSnippet,
        options: item.options,
        correctAnswer: item.correct,
        explanation: item.explanation,
        awsDocUrl: item.awsDocUrl,
        difficulty: i > 40 ? "Complex" : "Standard"
      });
    }
  }

  fs.writeFileSync(
    path.join(baseDir, 'dva-c02', `set-${setNum}.json`),
    JSON.stringify(questions, null, 2)
  );
}

// Generate sets 1-10 for DEA-C01 (65 questions per set: 50 Scored, 15 Unscored Beta)
for (let setNum = 1; setNum <= 10; setNum++) {
  const questions = [];

  for (let i = 1; i <= 65; i++) {
    const isScored = i <= 50; // 50 Scored Questions, 15 Unscored (Beta)
    const isMultiple = (i % 5 === 0);
    const topicIdx = (i + setNum) % deaTopics.length;
    const topic = deaTopics[topicIdx];
    const item = topic.scenarios[(i + setNum) % topic.scenarios.length];

    if (isMultiple) {
      questions.push({
        id: `dea-${setNum}-${i}`,
        setId: setNum,
        examCode: "DEA-C01",
        domainId: topic.domainId,
        domainName: topic.domainName,
        questionType: "multiple",
        selectCount: 2,
        isScored,
        scenario: `[DEA-C01 Set ${setNum} - Q${i}] A data engineering team is constructing an automated data lake ingestion pipeline on Amazon S3. Which TWO AWS services or features should be integrated to enforce centralized governance, column-level security, and data quality validation?`,
        options: [
          { id: "A", text: "AWS Lake Formation data cell filters for row and column-level permission masking." },
          { id: "B", text: "AWS Glue Data Quality rulesets to detect missing or malformed data records during ETL execution." },
          { id: "C", text: "Amazon Route 53 latency routing records." },
          { id: "D", text: "AWS Snowball Edge physical storage export devices." },
          { id: "E", text: "Amazon CloudFront distribution origins." }
        ],
        correctAnswer: ["A", "B"],
        explanation: "AWS Lake Formation provides centralized, granular row and column level security filters, while AWS Glue Data Quality automatically evaluates data quality metrics during ETL runs.",
        awsDocUrl: "https://docs.aws.amazon.com/lake-formation/latest/dg/data-filters-about.html",
        difficulty: i > 40 ? "Complex" : "Standard"
      });
    } else {
      questions.push({
        id: `dea-${setNum}-${i}`,
        setId: setNum,
        examCode: "DEA-C01",
        domainId: topic.domainId,
        domainName: topic.domainName,
        questionType: "single",
        isScored,
        scenario: `[DEA-C01 Set ${setNum} - Q${i}] ${item.scenario}`,
        codeSnippet: item.codeSnippet,
        options: item.options,
        correctAnswer: item.correct,
        explanation: item.explanation,
        awsDocUrl: item.awsDocUrl,
        difficulty: i > 40 ? "Complex" : "Standard"
      });
    }
  }

  fs.writeFileSync(
    path.join(baseDir, 'dea-c01', `set-${setNum}.json`),
    JSON.stringify(questions, null, 2)
  );
}

console.log("Successfully generated all 20 question sets (65 questions each: 50 Scored, 15 Unscored) for DVA-C02 & DEA-C01!");
